services:
  frontend-user:
    build:
      context: ./frontend-user
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    container_name: christmas-tree-user
    ports:
      - "8081:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
